- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/cli.rb
- sorbet/rbi/manual.rbi
- spec/lib/code_ownership/cli_spec.rb
The goal of this is to power a VSCode Extension to show ownership of a file.
```
~/workspace/zenpayroll - (ae-experiment-with-code-ownership-cli) $ bin/codeownership for_file packs/feature_flags/app/services/features/enabled.rb 
Team: Product Infrastructure
Team YML: config/teams/foundation/product_infrastructure.yml
~/workspace/zenpayroll - (ae-experiment-with-code-ownership-cli) $ bin/codeownership for_file packs/feature_flags/app/services/features/enabled.rb --json
{"team_name":"Product Infrastructure","team_yml":"config/teams/foundation/product_infrastructure.yml"}
```
I'd love reviewers to let me know if this is a good public API for this extension, keeping in mind questions like:
- Will this let me add an `errors` key that will allow the extension to also show code ownership errors …
> Add `bin/codeownership for_file` CLI to power extension

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/cli.rb
- spec/lib/code_ownership/cli_spec.rb
Some users have been confused when `bin/codeownership` doesn't produce the output they expect. This PR attempts to make this clearer by providing a help menu when no command is entered and an error message if an unrecognized command is outputted.
> Improve CLI UX by more providing feedback when an unrecognized command is used

- Gemfile.lock
- sorbet/rbi/gems/parse_packwerk@0.12.0.rbi
- spec/spec_helper.rb
Tests still pass and the version constraint on parse_packwerk isn't too tight, so no need to release a new version.
> Bump parse_packwerk

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/private/ownership_mappers/package_ownership.rb
- spec/lib/code_ownership_spec.rb
- spec/support/application_fixtures.rb
I was looking into whether nested packs would break package ownership. I realized that our old implementation of getting the owner of one file used a trie. I think this *would* work for nested packs, because it would find the nearest pack. However, I was worried things might start to fail when a file is a child of a parent pack and a child pack.
I think in practice, a parent pack probably should not be owned until all of the children packs are owned by the same team -- I **think** that's probably the only thing that makes sense. We could look into fixing this.
In the meantime, I found that our old implementation was convoluted, and actually slower than an implementation we had in `ParsePackwerk`.
```ruby
require 'code_ownership'
require 'benchmark'
all_files = Dir['packs/**/*.rb']; …
```
> Use ParsePackwerk function for package owner implementation

- README.md
- lib/code_ownership.rb
- lib/code_ownership/cli.rb
- spec/lib/code_ownership/cli_spec.rb
- spec/lib/code_ownership_spec.rb
This was inspired by some rake tasks we had within the Gusto monolith to get ownership reports for a team.
This seems like a valuable thing to upstream.
Right now, this is a simple report that just goes through each "mapper" type and prints out ownership based on codeowners line. Reusing the codeowners interface felt reasonable here.
This prints the information out as a simple markdown for easy viewing.
Example in Gusto's codebase: https://github.com/Gusto/zenpayroll/pull/160107
> Create bin/codeownership for_team for code ownership reports

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/cli.rb
Something in our test suite was requiring this, but this causes a failure when using in an application that doesn't explicitly require `fileutils` somewhere.
> Require FileUtils explicitly

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership.rb
- spec/lib/code_ownership_spec.rb
The intent is to expose more data and enable a consumer to report additional information. For example, we wish to use this method to log the "blamed" stack of an error.
> Introduce `CodeOwnership#first_owned_file_for_backtrace`

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/private.rb
- lib/code_ownership/private/ownership_mappers/team_globs.rb
- lib/code_ownership/private/validations/no_overlapping_globs.rb
- spec/lib/code_ownership_spec.rb
I recently identified a bug with the "files have unique owners" validation.
While the existing validation prevented different mappers from mapping the same file, it didn't prevent the same mapper from mapping the same file in different ways.
That is – it was still possible to have multiple teams' `owned_globs` map the same file. Based on an arbitrary load order (alphabetical, I suppose), one team was chosen as the owner.
This violates the intended explicit nature of ownership.
Therefore this PR ensures that `owned_globs` are mutually exclusive, preventing ownership errors.
This is pretty unique to the `TeamGlobs` mapper, so I chose to implement this as a standalone validation.
> Fix bug with "files have unique owners" validation

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/private.rb
- lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb
- spec/lib/code_ownership_spec.rb
I realized teams were not getting tagged when their team YML files were updated. Teams should be owning their own configuration, especially since that configuration itself contains ownership information, which teams should be aware of when it is changed.
This PR fixes this bug by adding a new mapper that explicitly marks team YML files as being owned by teams.
> Fix bug where team YML files are considered unowned

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership.rb
- lib/code_ownership/private.rb
- spec/lib/code_ownership_spec.rb
- spec/support/application_fixtures.rb
Now that an extension can add new mappers, we want to load the configuration explicitly before calling public APIs.
> Load configuration before calling public APIs

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership.rb
- lib/code_ownership/mapper.rb
- lib/code_ownership/private.rb
- lib/code_ownership/private/codeowners_file.rb
- lib/code_ownership/private/glob_cache.rb
- lib/code_ownership/private/ownership_mappers/file_annotations.rb
- lib/code_ownership/private/ownership_mappers/js_package_ownership.rb
- lib/code_ownership/private/ownership_mappers/package_ownership.rb
- lib/code_ownership/private/ownership_mappers/team_globs.rb
- lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb
- spec/lib/code_ownership/private/extension_loader_spec.rb
- spec/lib/code_ownership/private/validations/files_have_unique_owners_spec.rb
This PR allows the codeowners file to be used as a cache during validations. After pulling up the cache, we ask each mapper to update that cache given the input files. Then we use that cache to run our various validations.
> Use Codeowners file as incremental cache during validations

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership.rb
- lib/code_ownership/cli.rb
- lib/code_ownership/private.rb
- lib/code_ownership/private/glob_cache.rb
- lib/code_ownership/private/ownership_mappers/file_annotations.rb
- lib/code_ownership/private/validations/files_have_owners.rb
- lib/code_ownership/private/validations/files_have_unique_owners.rb
- spec/lib/code_ownership/cli_spec.rb
- spec/lib/code_ownership/private/validations/files_have_owners_spec.rb
Local benchmarking showed that globbing out files takes a *long time* in Gusto's large monolith (about 6 seconds). We can simply use File.fnmatch instead to determine if we need to consider a file when using `--diff`. This brings the speed down to about 1.3 seconds in Gusto's monolith during the commit hook!
> Do not glob out files unnecessarily

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/private/ownership_mappers/file_annotations.rb
- lib/code_ownership/private/ownership_mappers/package_ownership.rb
- lib/code_ownership/private/ownership_mappers/team_globs.rb
- lib/code_ownership/private/ownership_mappers/team_yml_ownership.rb
This removes some unnecessary caching, now that things are using the glob cache.
Note we'll be able to remove *all* of the class-var caching with some upcoming changes!
> Remove some unnecessary caching

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/private.rb
- spec/lib/code_ownership_spec.rb
When mocking controllers in Rspec, the class may be constructed in code, which means a class may look like `#<Class:0x000000015ea185d8>`, causing `Object.const_source_location` to fail. These should just return nil
> Return nil if class constant cannot be found

- README.md
Relates to #76. Documents how JS package ownership can be disabled/ignored.
> Add note about disabling js package ownership

- Gemfile.lock
- code_ownership.gemspec
- lib/code_ownership/configuration.rb
- lib/code_ownership/private/team_plugins/github.rb
- spec/lib/code_ownership/private/validations/github_codeowners_up_to_date_spec.rb
The Github CodeTeam Plugin only enforces that more than one CodeTeam does not have a duplicate `github.team` value. The validation error message is not specific if more than one CodeTeam do not have `github.team` keys. 
Given two CodeTeam YAML files with no `github.team` key, the validation errors produces the follow error message:
```ruby
irb(main):001:0>  CodeTeams.validation_errors(CodeTeams.all)
=> ["The following teams are specified multiple times:\nEach code team must have a unique GitHub team in order to write the CODEOWNERS file correctly.\n\n\n"]
```
It is not clear which CodeTeams are the offenders.
Update the Plugin to check that each CodeTeam has a `github.team` key.
```ruby
irb(main):001:0> CodeTeams.validation_errors(CodeTeams.all)
=>
["The following teams are missing …
```
> Update Github CodeTeam Plugin to enforce `github.team` presence

- lib/code_ownership/private/glob_cache.rb
- spec/lib/code_ownership/private/validations/files_have_unique_owners_spec.rb
Fixes https://github.com/rubyatscale/code_ownership/issues/90
When the `mapper_descriptions_that_map_files` method is called with an array of files, it should only return the portion of the cache the matches those files.
> restrict mappers to files that are actually in param

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/stale.yml
- .github/workflows/triage.yml
This repo doesn't use Rubocop, so we can't use the shared config for CI. I created an issue to track: https://github.com/rubyatscale/code_ownership/issues/99
> use shared config for cd, stale, triage

- lib/code_ownership/private.rb
- spec/lib/code_ownership/cli_spec.rb
When multiple owned globs are present `file_tracked?` expects a given file to be present in every owned glob. This leads to differing behavior between `file_tracked? file` and `tracked_files.include? file`.
Based on the comments and my experience trying to use the cli with `validate --diff`, I think the implementation in `file_tracked?` should be changed to match the behavior of the other methods that check for file inclusion.
> Fix `validate --diff` when multiple owned globs are present

- code_ownership.gemspec
- lib/code_ownership/private/glob_cache.rb
- spec/lib/code_ownership/private/validations/files_have_unique_owners_spec.rb
- spec/lib/code_ownership_spec.rb
This gem uses a different strategy to map files to ownership definitions depending on how many files are in the codebase. The two paths are not equally well-tested, and we've run into issues when their behavior diverges slightly.
Using `File.fnmatch` is supposed to be faster in small projects. Maybe there was more of a difference when this code was originally written, but at least on my machine today there doesn't seem to be much benefit. This PR removes the `File.fnmatch` path to simplify the gem and improve our confidence in the tests.
On a project with one file:
```bash
$ time bin/codeownership validate
using expanded cache
using expanded cache
real    0m0.456s
user    0m0.168s
sys     0m0.119s
$ time bin/codeownership validate
using File.fnmatch
using File.fnmatch
real    0m0.474s …
```
> always use expanded cache when getting mapper descriptions for files

- code_ownership.gemspec
- lib/code_ownership/private/ownership_mappers/directory_ownership.rb
- spec/lib/code_ownership_spec.rb
Globs can contain certain regex characters, like "[" and "]". However, when we are generating a glob from a .codeowners file, we need to escape bracket characters and interpret them literally. Otherwise the resulting glob will not actually match the directory containing the .codeowners file.
* Fixes https://github.com/rubyatscale/code_ownership/issues/103
```
file: "/some/[dir]/.codeowner"
unescaped: "/some/[dir]/**/**"
matches: "/some/d/file"
matches: "/some/i/file"
matches: "/some/r/file"
does not match!: "/some/[dir]/file"
```
> escape globs derived from .codeowner files

- code_ownership.gemspec
- lib/code_ownership/private.rb
- lib/code_ownership/private/ownership_mappers/file_annotations.rb
- spec/lib/code_ownership/private/ownership_mappers/file_annotations_spec.rb
When a file has special characters (brackets in this case) escaped with a backslash (e.g. `\[taskId\]`), the file shows the appropriate owner on Github.
When a file has special characters that are not escaped (e.g. `[taskId]`), it does not show an owner on Github.
Modifies `code_ownership` to escape special characters for files with ownership declared with file annotations. This change was already made for escaping globs derived from .codeowner files: https://github.com/rubyatscale/code_ownership/pull/106
> escape brackets for files owned with a file annotation

- code_ownership.gemspec
- lib/code_ownership/private/codeowners_file.rb
- spec/lib/code_ownership/private/validations/github_codeowners_up_to_date_spec.rb
- spec/lib/code_ownership_spec.rb
- spec/support/application_fixtures.rb
`/frontend/packages/my-thing/src/pages/blah` is owned by Foo via a `.codeowner` file
`/frontend/packages/my-thing/src/pages/blah/(bar)` is owned by Bar via a `.codeowner` file
The most specific (nested) `.codeowner` file should take precedence, so `/frontend/packages/my-thing/src/pages/blah/(bar)/Sidebar.test.tsx` should be owned by Bar.
`/frontend/packages/my-thing/src/pages/blah/(bar)/Sidebar.test.tsx` shows that it is owned by Foo. This is because `/frontend/packages/my-thing/src/pages/blah/(bar)` is written above `/frontend/packages/my-thing/src/pages/blah` in the `CODEOWNERS` file.
This change updates the file sorting such that if two globs match up until a `**`, then the one without the `**` at that location will be prioritized. This ensures that the more specific folder will come …
> Add special sorting for special characters in globs

- .github/workflows/ci.yml
- code_ownership.gemspec
- lib/code_ownership.rb
Ruby 3.4 changes backtrace from using backtick to single quote, fix our regex and use simple if/else to make it compatible with ruby 3.4.
> feat: match ruby 3.4 backtrace changes

- README.md
- code_ownership.gemspec
- lib/code_ownership/configuration.rb
- lib/code_ownership/private/codeowners_file.rb
- spec/lib/code_ownership/private/codeowners_file_spec.rb
The current version of the gem always defaults `CODEOWNERS` to generate in `.github/CODEOWNERS`. This works well for projects that follow the same structure but doesn't work well for other structures (or other platforms). For example:
- [Github works with `CODEOWNERS` in `.github/`, `docs/` or root.](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-file-location)
- [Gitlab works with `CODEOWNERS` in `.gitlab/`, `docs/` or root.](https://docs.gitlab.com/ee/user/project/codeowners/#codeowners-file)
This change updates the path for the file location to pull from an environment variable (`CODEOWNERS_PATH`) to use for the path. It will still default to the old behavior of using `.github/` to …
> Use environment variable to set CODEOWNERS write path

- lib/code_ownership/private/ownership_mappers/file_annotations.rb
- spec/lib/code_ownership/private/ownership_mappers/file_annotations_spec.rb
This PR adds [HAML comment syntax](https://haml.info/docs/yardoc/file.REFERENCE.html#haml-comments--) to the `TEAM_PATTERN` Regex, along with corresponding tests.
> Support ownership for HAML files

- spec/lib/code_ownership/private/ownership_mappers/js_package_ownership_spec.rb
We were checking for specific text in the JSONParseError, but when json was updated, the message changed. We really only care that there was a JSON parse error so we're shortening the string we're checking. This change will make it so we don't run into this error again in future version updates.
> Fix JSON spec

- .gitignore
- lib/code_ownership/private/ownership_mappers/team_globs.rb
- lib/code_ownership/private/team_plugins/ownership.rb
- spec/lib/code_ownership/private/ownership_mappers/team_globs_spec.rb
This adds the ability to specify `unowned_globs` for a team. The primary use case of this is to allow more granularity in how ownership globs are defined.
Suppose you want Team A to own everything that has a folder named `foo` in the path, so you would define a glob like: `**/foo/**/*` but at the same time, you want Team B to own everything in a specific folder, regardless if it has a `foo` folder in it or not. So you would define a glob like: `shared/**/*`, but if it actually has a `foo` folder in it, then the validation would complain that you cannot have overlapping ownership between teams.
With this, you can now specify that Team does not own `shared/**/foo/*` and everyone is happy.
To the best of my knowledge, nothing needs to change in the `CODEOWNERS` generation, since it already …
> feat: add concept of unowned globs to team configs

- lib/code_ownership/private/ownership_mappers/file_annotations.rb
- spec/lib/code_ownership/private/ownership_mappers/file_annotations_spec.rb
Errno::ENOENT is occuring intermittently for some users. This is happening even when the file seems to exist at the time
Since we were already returning quietly if a file did not exist, just try to read the file and rescue exceptions, returning silently.
Fixes #98
> Ignore ENOENT when reading file annotations

- code_ownership.gemspec
- lib/code_ownership/private/owner_assigner.rb
- lib/code_ownership/private/ownership_mappers/team_globs.rb
@martinemde says that this change will make these globs a bit faster which is important when you're running this on a large codebase.
> update the way we glob team files

- README.md
We forgot to update the readme as part of the change to #117. Adding a self-explaining example.
> Update README.md for unowned team globs

- .github/workflows/cd.yml
CD has a check that matches the gem version to release tag. CD exits early if they don't match.
This  PR updates the regex to allow for pre-releases of the form `2.0.0-1` and fixes the path to the version.rb
> Allow for pre-releases

- Cargo.lock
- ext/code_ownership/Cargo.toml
- ext/code_ownership/src/lib.rs
- lib/code_ownership.rb
- lib/code_ownership/cli.rb
- lib/code_ownership/private/for_file_output_builder.rb
- lib/code_ownership/version.rb
- spec/lib/code_ownership/cli_spec.rb
Updates codeowners-rs to version 0.2.14, which includes:
---
- support for ERB file annotations
- file annotation can contain a `:` after team. Example: `# team: Foo`
- unstaged files are ignored
New verbose flag
---
`bin/codeownership for_file --verbose path/to/file.rb` prints out the reason for ownership
Example:
```sh
bin/codeowners for-file my/file.rb
Team: Foo
Github Team: @foo
Team YML: config/teams/foo.yml
Description:
- Owner annotation at the top of the file
```
> Update codeowners-rs  and new for_file --verbose option

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- Cargo.lock
- ext/code_ownership/Cargo.toml
- ext/code_ownership/src/lib.rs
- lib/code_ownership.rb
- lib/code_ownership/cli.rb
- lib/code_ownership/private/for_file_output_builder.rb
- lib/code_ownership/private/team_finder.rb
- lib/code_ownership/version.rb
- sorbet/rbi/manual.rbi
- spec/lib/code_ownership/cli_spec.rb
- spec/lib/code_ownership_spec.rb
This pull request introduces several improvements and new features to the code ownership infrastructure, focusing on performance, usability, and maintainability. The most significant changes include a new bulk ownership lookup API for files, enhanced documentation and parameterization for ownership queries, workflow optimizations for CI/CD, and dependency updates for the Rust backend. These changes make ownership queries faster and more flexible, improve the artifact publishing and release process, and add more robust validation and error handling.
**Features & API Improvements**
* Added bulk ownership lookup: Implemented `teams_for_files` in the Rust extension and exposed `teams_for_files_from_codeowners` in Ruby, allowing efficient ownership queries for multiple files at once. This is …
> Teams for file paths

- .github/workflows/cd.yml
This pull request introduces a minor update to the GitHub Actions workflow configuration. The change adds support for manually triggering the continuous deployment workflow.
* Added the `workflow_dispatch` event to `.github/workflows/cd.yml`, enabling manual workflow runs.
> Allow manual CD triggering
